apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  labels: 
    vol: mysql
spec: 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.66
    path: "/export"
