apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
spec: 
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.66
    path: "/export"
