apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: helloworld
    namespace: awsaug
spec: 
    replicas: 3
    selector: 
      matchLabels: 
         app: helloworld-pod
    template: 
      metadata: 
        labels:
          app: helloworld-pod
      spec:  
        containers:
        - name: helloworld
          image: iqbal1m/awwsjuly:devops
